### PR TITLE
 Add SSL certificate for AWS China to redshift-ca-bundle.crt

### PR DESCRIPTION
**Pull request by xz278**
## Todos
- [x] MIT compatible
- [x] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

The certificate is downloaded from AWS China official website at https://docs.amazonaws.cn/en_us/redshift/latest/mgmt/connecting-ssl-support.html

### CODE REVIEW

**Comment by jklukas** [comment]
I don't deeply understand the implications of adding this cert to the default list, but I assume Amazon has good reasons for deploying the cn-north-1 cert separately from the main bundle. I think users will need to configure the bundle separately to support this case.

**Comment by graingert** [comment]
Is it possible to enable this cert only for Amazon.ch redshift instances?

**Comment by totogo** [comment]
> 
> 
> I don't deeply understand the implications of adding this cert to the default list, but I assume Amazon has good reasons for deploying the cn-north-1 cert separately from the main bundle. I think users will need to configure the bundle separately to support this case.

Due to regulation issues, Amazon data center in China is actually operated by local companies rather than Amazon itself, so the certificates are different with the rest of AWS. Without these certificate, we go an error when we try to connect Redshift in China region. 
```
 {"error": "Connection failed!
 The error message returned was:
 (psycopg2.OperationalError) SSL error: certificate verify failed

 (Background on this error at: http://sqlalche.me/e/e3q8)", "stacktrace": "Traceback (most recent call last):
   File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2265, in _wrap_pool_connect
     return fn()
....
```
We are using Superset with Redshift in AWS China, which relies on ```sqlalchemy-redshift```. We have to build our own process to add these certificates every time when there is an update, which is really cumbersome. 

We appreciate you could add this in the main bundle to support Redshift in AWS China.

**Comment by jklukas** [comment]
> Amazon data center in China is actually operated by local companies rather than Amazon itself

That would explain why Amazon doesn't trust that certificate by default in their bundles. I imagine they want customers to opt-in to trusting that additional party. Given that, I want the same for users of sqlalchemy-redshift; I don't want them to trust a certificate for an additional party beyond Amazon without explicitly opting in.

I would be very much open to suggestions/PRs that make it easier for sqlalchemy-redshift users to opt in to trusting the additional party, but it doesn't sound appropriate to make this a default.

**Pull request closed without merging**
