### PR TITLE
add acm cert bundle

### PR DESCRIPTION
**Pull request by rhockenbury**
## Todos
- [ ] MIT compatible
- [ ] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

### CODE REVIEW

**Comment by jklukas** [comment]
I'll pull this down and run tests against the cluster.

**Comment by rhockenbury** [comment]
@graingert 

Updated.

**Comment by jklukas** [comment]
I'm seeing errors when running the tests against Redshift which look entirely unrelated:
```
E       assert 'CREATE TABLE...ISTSTYLE EVEN' == 'CREATE TABLE ...ISTSTYLE EVEN'
E         Skipping 89 identical leading characters in diff, use -v to show
E         -  INTEGER, CONSTRAINT reflection_composite_fk_constraint_pkey PRIMARY KEY (id), CONSTRAINT reflection_composite_fk_constraint_col1_fkey FOREIGN KEY(col1, col2) REFERENCES reflection_pk_constraint (col1, col2) ) DISTSTYLE EVEN
E         +  INTEGER, PRIMARY KEY (id), FOREIGN KEY(col1, col2) REFERENCES reflection_pk_constraint (col1, col2) ) DISTSTYLE EVEN
```

Could this be a regression from a recent change in this repo, or does this look like a change in Redshift's behavior? It looks like constraints are being returned differently.

**Comment by jklukas** [comment]
Travis is showing InterpreterNotFound errors, which I've also not seen.

**Comment by rhockenbury** [comment]
Looking at the travis logs, I'm seeing:

E: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  503  Service Unavailable [IP: 140.211.166.134 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jklukas** [comment]
I'm getting the errors discussed in https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/130#issuecomment-330875976 when running master branch tests against Redshift, so I think something changed with Redshift itself that will need to be fixed separately from this issue.

**Comment by mjschultz** [comment]
It would be nice to verify the new bundle against the new certs AWS will be using prior to them actually forcing everyone to changeover. From the email and page when I read it that doesn't seem possible right now (which scares me).

I can open a support issue inquiring about that ability unless you have that ability?

**Comment by jleclanche** [comment]
I've filed an alternative pr in #132 which cleans up the issues here and some other things.

**Comment by graingert** [comment]
closing in favor of #132

**Pull request closed without merging**
