### PR TITLE
Work-In-Progress fix broken reflection tests

### PR DESCRIPTION
**Pull request by waltaskew**
## Todos
- [ ] MIT compatible
- [ ] Tests
- [ ] Documentation
- [ ] Updated CHANGES.rst

### CODE REVIEW

**Comment by jklukas** [comment]
Are the tests broken, or is this due to transient spinup/spindown of our test Redshift cluster? It's often necessary to rerun tests because the test suite has to spin up the Redshift cluster before running, and then it automatically spins down after a period of being idle, blocking further tests for a bit.

**Comment by waltaskew** [comment]
> Are the tests broken, or is this due to transient spinup/spindown of our test Redshift cluster?

They look just straight broken:
https://travis-ci.org/sqlalchemy-redshift/sqlalchemy-redshift/builds/195497130

I was poking around, trying to see where the 'ENCODE lzo' stuff was coming from.

> Also you need to be a contributor to get the redshift cluster to spin up

I was just noticing that -- I created the PR so I could run the Redshift tests but noticed they were all skipped.

**Comment by graingert** [comment]
Strange encode lzo is probably something that amazon has added?

**Comment by waltaskew** [comment]
> Strange encode lzo is probably something that amazon has added?

Redshift has default encodings it will apply if none are supplied, which I think is what's happening here.

```
If no compression is specified in a CREATE TABLE or ALTER TABLE statement, Amazon Redshift automatically assigns compression encoding as follows:

Columns that are defined as sort keys are assigned RAW compression.
Columns that are defined as BOOLEAN, REAL, or DOUBLE PRECISION data types are assigned RAW compression.
All other columns are assigned LZO compression.
```

http://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html

**Comment by waltaskew** [comment]
I'd be down to get this sorted (I was thinking add some explicit encodings to the models in `rs_sqla_test_utils.models` and then update the expected DDL strings) but it looks like it'd be tricky for me since I can't spin up the redshift.

**Pull request closed without merging**
