### PR TITLE
Support GEOMETRY, SUPER Redshift datatypes

### LINKED ISSUE #209: Feature Request: Add Redshift GEOMETRY types
Feature request to add Redshift GEOMETRY type and subtypes as [vendor-specific types](https://docs.sqlalchemy.org/en/13/core/type_basics.html#vendor-specific-types). 

This probably has a lot of overlap with [geoalchemy2](https://geoalchemy-2.readthedocs.io/en/latest/). However, since spatial data types are now natively supported by Redshift, it would be good to have first-class support in the Redshift dialect to ensure there are no quirks.

From the [Redshift docs](https://docs.aws.amazon.com/redshift/latest/dg/geospatial-overview.html):

> Spatial data describes the position and shape of a geometry in a defined space (a spatial reference system). Amazon Redshift supports spatial data with the GEOMETRY data type, which contains spatial data and optionally its spatial reference system identifier (SRID).
> 
> Spatial data contains geometric data that can be used to represent geographic features. Examples of this type of data include weather reports, map directions, tweets with geographic positions, store locations, and airline routes. Spatial data plays an important role in business analytics, reporting, and forecasting...
>
> The GEOMETRY data type has the following subtypes:
>  * POINT
>  * LINESTRING
>  * POLYGON
>  * MULTIPOINT
>  * MULTILINESTRING
>  * MULTIPOLYGON
>  * GEOMETRYCOLLECTION

### PR DESCRIPTION
**Pull request by Brooke-white**
Closes #209, #224. Adds support for Redshift `SUPER` and `GEOMETRY` datatypes.

credit to @rectalogic for their approach for `SUPER` datatype support, which I've duplicated in this PR.

## Todos
- [x] MIT compatible
- [x] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

### CODE REVIEW

**Review by jklukas — APPROVED** [review]
Looks good. I just kicked off integration tests. If those look good, we can go ahead and merge.

**Comment by Brooke-white** [comment]
@jklukas -- did your test run for this change look ok?

**Comment by jklukas** [comment]
> @jklukas -- did your test run for this change look ok?

Thanks for the reminder. That run was flaky and errored out. I'm running a new one now. Note that since you now have commit access, you can make future PRs via a branch on this repo, which will automatically kick off the integration tests.

You can also kick off integation tests for forks by verifying that the content isn't malicious, and then pushing the changeset to a branch on this repo. I use https://github.com/jklukas/git-push-fork-to-upstream-branch to manage that workflow.

**Comment by jklukas** [comment]
This change is now released in 0.8.8

**Pull request merged**
