### PR TITLE
Add Support for CREATE TABLE AS statements

### PR DESCRIPTION
**Pull request by waltaskew**
## Todos
- [x] MIT compatible
- [x] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

Adds support for Redshift's CREATE TABLE AS statement
http://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_AS.html

I wasn't sure if something like
```python
import sqlalchemy_redshift.dialect

create = (dialect.create_table_as(name, query)
          .distkey('col')
          .sortkey('another_col'))
```
would be a little more sql-alchemy-y, but I was trying to stay between the lines of the UNLOAD and COPY statements provided by the package.

### CODE REVIEW

**Comment by jseabold** [comment]
@graingert Can you walk me through running the integration tests? Do you usually just create a new branch, push it, check the tests, then delete it before merging an PRs?

**Comment by graingert** [comment]
Only branches in this repo run the FTs because of the permissions needed on
redshift.

**Comment by jseabold** [comment]
Sure. So is the workflow I described above how you usually achieve this?

**Comment by graingert** [comment]
Sort of, but github deletes the branch for us

**Comment by jseabold** [comment]
Sorry I guess I'm still missing how you achieve this.

Asked in another way, how do you go from original PR made from a branch in someone's fork to a branch in this repository that runs the integration tests? All of the merged PRs I see come from forks.

It doesn't look like you make a branch locally, push it, and open a new PR.

Do you merge PRs to master then open a new PR from master to another branch from which you cut releases?

The only other thing I can think of is push the remote branch to this repo, check the tests, and delete the branch. I don't see how github deletes this branch unless that's part of a hook that I don't see.

**Comment by graingert** [comment]
@jseabold oh there's not really such a workflow, in your case I just gave you collaborator access.

**Comment by jklukas** [comment]
I just pushed a commit here to resolve conflict in CHANGES.rst

**Comment by waltaskew** [comment]
Does this seem like something folks would consider merging?  Anything I can do to help?

**Comment by waltaskew** [comment]
> Is there not an API from sqlalchemy that we can implement for create table as? What about Insert.from_select?

I don't see an API in sqlalchemy for this, which was a bit surprising to me. `Insert.from_select` inserts into an existing table.

**Comment by graingert** [comment]
@waltaskew can you stick with two separate table.create() Insert.from_select queries for now? Otherwise see if you can get sqlalchemy core to provide an API we can implement

**Comment by waltaskew** [comment]
> @waltaskew can you stick with two separate table.create() Insert.from_select queries for now? Otherwise see if you can get sqlalchemy core to provide an API we can implement

Yeah, should be possible to dynamically build a table object off of a selectable's `.columns` (as long as the query was built off of column objects rather than just column names as strings) and do a `table.create()` in a transaction with the inserts. It looks like Redshift does support doing DDL in a transaction.

This does seem like a slightly weird omission from the SQLAlchemy API.

**Pull request closed without merging**
