### PR TITLE
Override new upstream PGDialect._set_backslash_escapes() method

### PR DESCRIPTION
**Pull request by matthewgdv**
## Todos
- [x] MIT compatible
- [ ] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

Contributes towards #264 
Backwards-compatible with 1.4

Requires [this](https://github.com/sqlalchemy/sqlalchemy/pull/9475) upstream PR to be merged first

### CODE REVIEW

**Comment by matthewgdv** [comment]
Just coming back from being on holiday.

Was wondering if there's anything stopping us from merging this in? This change will improve our compatibility with the upcoming release of SqlAlchemy 2.0, by at least allowing us to open a connection.

**Comment by Brooke-white** [comment]
Nothing stopping us, I've just been held up with other tasks. I'll try to take a look early next week.

**Comment by Brooke-white** [comment]
running through CI now

**Review by Brooke-white — APPROVED** [review]
ci passing, thank you!

**Pull request merged**
