### PR TITLE
Remove psycopg2

### PR DESCRIPTION
**Pull request by mjschultz**
## Todos
- [x] MIT compatible
- [ ] Tests
- [ ] Documentation
- [ ] Updated CHANGES.rst

### CODE REVIEW

**Comment by jklukas** [comment]
Can you give me some more context on the approach here? My first thought is that it may be surprising to users that they need to install psycopg2 separately. It's still an open question what exactly the best approach is to give users flexibility  but ease of use around choosing psycopg2 vs. psycopg2-binary, etc.

**Comment by mjschultz** [comment]
I can't say if it's good or not, my thinking was mostly along the lines of sqlalchemy doesn't depend on every db driver being installed to work and users of sqlalchemy know that so it should be too much of a surprise that they'd need to install psycopg2 for this to work.

Beyond that, we _know_ it's annoying to users right now that there is a psycopg2/psycopg2-binary split upstream. So I figured let's fix something concrete now instead of waiting on something that may or may not be surprising in the future.

We could also enable something like `pip install  sqlalchemy-redshift[psycopg2]` and `pip install sqlalchemy-redshift[psycopg2-binary]` to have this bring in those dependencies. Maybe someday someone will get a pg8000 version working as well.

**Comment by stevebeck89** [comment]
This should be related to [issue 165](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/165)

I think it makes sense to simply require `sqlalchemy` and defer to the way it's handling the `psycopg2` dependency.  

Bumping this as it's causing my team problems.

**Comment by jklukas** [comment]
> I think it makes sense to simply require sqlalchemy and defer to the way it's handling the psycopg2 dependency.

I think I'm starting to agree with that position.

I'm not inclined to merge the PR as written here, as I don't see any benefit of factoring out `BaseRedshiftDialect` until we actually have an implementation for an additional driver.

If someone wants to submit a new PR for this problem, I think the essential elements are:

- Remove psycopg2 from the dependencies
- Add a note in the CHANGELOG indicating the removal of the dependency
- Add some documentation; probably just updating the Installation section of the README to indicate that it's necessary to install psycopg2 separately and to mention the difference between the binary and non-binary packages

And then we can release with a bump to the major version number.

**Comment by mjschultz** [comment]
> until we actually have an implementation for an additional driver

So the main motivator is to make it easier for other people to extend the base class that doesn't have the dialect baked in without having to modify the package itself or duplicate the code in their project carefully. The intent is to decrease the friction to create the other dialect so that it could be implemented. It's a relatively low cost code movement that enables future changes more easily.

**Comment by jklukas** [comment]
Closed by #172

**Comment by jklukas** [comment]
> So the main motivator is to make it easier for other people to extend the base class that doesn't have the dialect baked in without having to modify the package itself or duplicate the code in their project carefully. The intent is to decrease the friction to create the other dialect so that it could be implemented. It's a relatively low cost code movement that enables future changes more easily.

This makes sense to me. If you rebase this PR on master, change the title to reflect it being about creating BaseRedshiftDialect, and add a relevant line to CHANGES.rst, then I'd be willing to merge this.

**Pull request closed without merging**
