### PR TITLE
create PR template Fixes #81

### LINKED ISSUE #81: Add a CONTRIBUTING.md
For most PRs, we are requiring tests, documentation, and CHANGES.rst notes. Sometimes we ask for these upfront, but sometimes we forget until later in the review, and it delays merging good changes.

We should provide a CONTRIBUTING.md both as a checklist for those doing review to make sure they aren't forgetting things, and for contributors so that they don't feel like requirements are popping up out of nowhere.

cc @graingert

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by jklukas** [comment]
Should the content here be in CONTRIBUTING.md so that a banner appears pointing to it when folks open a new issue or pull request?

**Comment by graingert** [comment]
@jklukas I think that a PR template is more appropriate. It gives reviewers and contributors check-boxes to complete.

**Comment by jklukas** [comment]
I hadn't realized that Pull Request templates were actually a thing now. This is amazing!

**Comment by jklukas** [comment]
+1

**Pull request merged**
