### PR TITLE
Format exception string

### PR DESCRIPTION
**Pull request by adrizein**
## Todos
- [x] MIT compatible
- [ ] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

The string description of the ValueError raised in _get_schema_and_relation is not formatted, so the exception is unreadable when raised.
The error would originially display "ValueError: %s does not look like a valid relation identifier".
Now, if key is "&#foobar", the error will be displayed as: "ValueError: &#foobar does not look like a valid relation identifier".

### CODE REVIEW

**Comment by graingert** [comment]
@adrizein nice, any change of a cheeky test?
(Tick all the remaining boxen)

**Comment by graingert** [comment]
:tada: Congratulations on your first contribution @adrizein :tada: :cake: :zap:

**Comment by graingert** [comment]
@adrizein ...?

**Comment by adrizein** [comment]
Sorry, I don't have any tests for this and I don't have access to the code that raised the exception anymore...

**Comment by graingert** [comment]
@adrizein can you rebase this?

**Comment by graingert** [comment]
This doesn't look right

**Comment by adrizein** [comment]
I think the code has changed too much since my original pull request, there is no need for it anymore.

**Pull request closed without merging**
