### PR TITLE
Pass in info_cache when querying constraints.

### PR DESCRIPTION
**Pull request by jklukas**
## Todos
- [x] MIT compatible
- [x] Tests
- [x] Documentation
- [x] Updated CHANGES.rst

Addresses https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/101

Existing tests already exercise this reflection code, so I don't think additional tests are necessary. Also no documentation changes other than adding a note in the changelog.

### CODE REVIEW

**Comment by atrigent** [comment]
Looks good to me, although the name of the thing that wasn't getting passed in is `info_cache`, not `cache_info`.

**Comment by jklukas** [comment]
> Looks good to me, although the name of the thing that wasn't getting passed in is info_cache, not cache_info.

Noted and updated title.

**Comment by jklukas** [comment]
cc @graingert @solackerman @jseabold @scribu for any of those folks who might like to review.

**Comment by solackerman** [comment]
👍

**Comment by graingert** [comment]
@jklukas slick.

**Pull request merged**
