### PR TITLE
Require enum34 explicitly

### PR DESCRIPTION
**Pull request by jcalero**
I doubt anyone cares, but this is the only way I can get it to work in our ancient version of setuptools.

### CODE REVIEW

**Comment by graingert** [comment]
> our ancient version of setuptools.

**Comment by graingert** [comment]
have you tried:

```python
pip install -U pip setuptools wheel
```

**Comment by graingert** [comment]
otherwise we could use something like:

https://github.com/kevin1024/vcrpy/blob/ef727aaaafe5dd1bf07e152b3ef8c738806de78d/setup.py#L38-L50

**Comment by jcalero** [comment]
I'm sorry, this was meant to be a PR to our fork! Very embarrassing! :grin: 

Thanks but we have our entire infrastructure "stuck" on setuptools 19.2, which is on the pipeline to be upgraded but unfortunately isn't as easy as just pip upgrading it.

**Pull request closed without merging**
